

title: My Musings on Baseball, Data, and Life
email: donaldjshaw7@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog about baseball data, geography, life, literature, and other weird things I think about.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  don-shaw

# Build settings
theme: minima
plugins:
  - jekyll-feed

